### ISSUE TITLE
V2 API Checklist

### ISSUE THREAD

**Issue by ahonn** [utxostack/btc-assets-api#185]
## Todo
- [ ] UTXO Stack support
- [ ] Unified naming of interface parameters and response
  related discussion: https://github.com/ckb-cell/btc-assets-api/pull/184#discussion_r1664944321
  - [ ] https://github.com/ckb-cell/btc-assets-api/pull/184#discussion_r1664987102
  - [x] https://github.com/ckb-cell/btc-assets-api/pull/184#discussion_r1664991221
- [ ] decentralized RGB++ CKB transaction queue
  To store the queue data in a decentralized manner, a few potential solutions include:
  1. The queue data could be pinned to IPFS (InterPlanetary File System)
  2. The queue could utilize a WebSocket PubSub (Publish-Subscribe) system between assets-api nodes to enable real-time communication between the queue and its subscribers.
